create table authorities (id bigint generated by default as identity, name varchar(255), primary key (id))
create table categories (id bigint generated by default as identity, name varchar(255), user_id bigint, primary key (id))
create table entries (id bigint generated by default as identity, description varchar(255), category_id bigint, user_id bigint not null, primary key (id))
create table roles (id bigint generated by default as identity, name varchar(255), primary key (id))
create table roles_authorities (role_id bigint not null, authority_id bigint not null)
create table users (id bigint generated by default as identity, email varchar(255), firstname varchar(255), lastname varchar(255), password varchar(255), primary key (id))
create table users_roles (user_id bigint not null, role_id bigint not null)
alter table users drop constraint if exists UK_6dotkott2kjsp8vw4d0m25fb7
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table categories add constraint FKghuylkwuedgl2qahxjt8g41kb foreign key (user_id) references users
alter table entries add constraint FKfc6r6cf8c0hq0s2n3i5unfgss foreign key (category_id) references categories
alter table entries add constraint FKoia5s1p9sk4x5fld87yjqpjg9 foreign key (user_id) references users
alter table roles_authorities add constraint FKt69njxcgfcto5wcrd9ocmb35h foreign key (authority_id) references authorities
alter table roles_authorities add constraint FKq3iqpff34tgtkvnn545a648cb foreign key (role_id) references roles
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users