create table category
(
    id      bigint generated by default as identity,
    name    varchar(255),
    user_id bigint,
    primary key (id)
);
create table entries
(
    id          bigint generated by default as identity,
    description varchar(255),
    category_id bigint,
    user_id     bigint not null,
    primary key (id)
);
create table permissoes
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table roles
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table roles_privileges
(
    role_id      bigint not null,
    privilege_id bigint not null
);
create table users
(
    id        bigint generated by default as identity,
    email     varchar(255),
    firstname varchar(255),
    lastname  varchar(255),
    password  varchar(255),
    primary key (id)
);
create table users_roles
(
    user_id bigint not null,
    role_id bigint not null
);
alter table users
    add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table category
    add constraint FK7ffrpnxaflomhdh0qfk2jcndo foreign key (user_id) references users;
alter table entries
    add constraint FKxsmpd6k3vgvuh7q6ygynwsnh foreign key (category_id) references category;
alter table entries
    add constraint FKoia5s1p9sk4x5fld87yjqpjg9 foreign key (user_id) references users;
alter table roles_privileges
    add constraint FKnp0a2atstha1t9y51kc3msp20 foreign key (privilege_id) references permissoes;
alter table roles_privileges
    add constraint FK629oqwrudgp5u7tewl07ayugj foreign key (role_id) references roles;
alter table users_roles
    add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles;
alter table users_roles
    add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;